name: build & test

on:
    push:
        branches: ["main"]

    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    build_app:
        name: Node ${{ matrix.node-version }} build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Packages
              run: |
                  cd ./app
                  pwd
                  npm ci

            - name: Build Angular App
              run: |
                  cd ./app
                  pwd
                  npm run build

